[package]
name = "enchant-sys"
version = "0.2.0"
authors = ["Jan Tojnar <jtojnar@gmail.com>"]
description = "FFI bindings to Enchant"
license = "LGPL-2.1"
links = "enchant"

[build-dependencies]
pkg-config = "0.3"
